import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Toaster } from "react-hot-toast";
import LogoutButton from "@/components/logout-button";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Turborepo",
	description: "Generated by create turbo",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${geist.className} container mx-auto p-4`}>
				<LogoutButton />
				{children}
				<Toaster />
			</body>
		</html>
	);
}
